version: 2
jobs:
  build:
    docker:
      - image: 552172703831.dkr.ecr.us-west-2.amazonaws.com/infra-tools:latest
    steps:
      - checkout
      - run:
          name: Greeting
          command: echo Hello, world.
      - run:
          name: Print the Current Time
          command: date
      - run:
          name: Chef Version
          command: chef -v
      - run:
          name: pip Version
          command: pip --version
      - run:
          name: Packer Version
          command: packer -v
      - run:
          name: Terraform Version
          command: terraform -v
      - run:
          name: Terragrunt Version
          command: terragrunt -v

